### ISSUE TITLE
 I and Iˆ

### ISSUE THREAD

**Issue by yc123237** [fourson/Learning-to-dehaze-with-polarization#1]
Hello:)
First, thank you for making and revealing the  dehazing net!
In experiments,learning-based methods are  using Iˆ as input. How to calculate Iˆ ,whether use Equation(8).
what's the difference between  I and Iˆ.
Iˆ are polarized picture?

**Comment by fourson** [comment]
Iˆ is the computed unpolarized hazy image from three polarized hazy images (I_\alpha1,2,3) using a linear system obtained from Equation(8).
We use Iˆ to denote the computed unpolarized image, which is different from the ground truth polarized hazy image (I) for evaluation on synthetic data. Note that Iˆ is not equal to I since the computed Iˆ would be noisy due to the noise of I_\alpha1,2,3.
