### ISSUE TITLE
 There are some differences in results

### ISSUE THREAD

**Issue by xdyfazio** [fourson/Learning-to-dehaze-with-polarization#6]
Hello, after using the full.path provided by you and the synthetic polarization data set generated by myself (according to readme.md), the test result is PSNR:29.54 MS_SSIM:0.9671, which is higher than the result in the paper. However, I use my own trained full.path, PSNR performance is only 26.85,MS_SSIM is basically similar: 0.953. I would like to know the reasons for the high test performance and low training performance. I preliminarily speculate that some random numbers were introduced in the synthesis of the data set, so that my final synthesis of the polarization data set is not exactly the same as the one you used. If this is the case, can you provide the resultant polarization data set? Or maybe you have other ideas. Hope to get your reply.

**Comment by fourson** [comment]
Hello there,
It seems that this is because the differences produced by the random factors would influence the results. Since this work was done in three years ago, I only store some test samples locally, and the whole original dataset in the server is not available now.
If you aim to compare to our method you can just re-train it to a reasonable status.
